exclude: [CNAME, config.rb, Gemfile, Gemfile.lock, LICENSE.txt, Rakefile, README.md]
highlighter: pygments
paginate: 10
paginate_path: ":num"
title: "dSpace Labs"
email: "joshua@dspacelabs.com"
author: "Joshua Estes"
description: "dSpace Labs"
baseurl: ""
url: "http://dspacelabs.com"
date_format: "%b %-d, %Y"

# Google services
google_analytics: UA-51216623-6
google_verification:

# Optional features
animated:             false
show_related_posts:   true
show_post_footers:    true
show_social_icons:    true
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username:  "dSpaceLabs"
bitbucket_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: /:year/:month/:day/:title/
paginate:     4
sass:
  compressed: true
